### ISSUE TITLE
make missiles more intuitive

### ISSUE THREAD

**Issue by mwcz** [ScriptaGames/pityaboutearth#33]
The "missile command" behavior of missiles is confusing to just about everyone.  Let's make the missile behavior more intuitive.

- [x] give some visual feedback at the point of the click
- [ ] (optional) give missiles windy paths (something like [this](https://youtu.be/XultudO2PFQ?t=7m46s))

**Comment by mwcz** [comment]
@Jared-Sprague here's the effect I added, let me know what you think:

![missile-target](https://cloud.githubusercontent.com/assets/364615/26022267/e2008022-376e-11e7-9cc9-58aefdce999f.gif)

it's in branch `missile-target-33`

**Comment by Jared-Sprague** [comment]
I love it!

**Comment by Jared-Sprague** [comment]
@mwcz I think what would be even cooler, is if we made the curse a triangle cross-hairs that match the animation.  I think with those combined people will intuitively know that it's targeting a point

**Comment by mwcz** [comment]
@Jared-Sprague great idea!  Chrome has some bothersome limitations on using PNGs as cursors, but I'll see what I can do!

**Comment by mwcz** [comment]
@Jared-Sprague hey, I tried a bunch of different crosshair ideas, but in the end went with a simple red dot.  Very happy to change it if you have a better idea.  I'm kinda stumped on what the cursor should look like so that it looks like a targeting crosshair, but doesn't block view of the triangulation animation.

![missile-target2](https://cloud.githubusercontent.com/assets/364615/26031122/c9e2c4f6-3835-11e7-9175-be7958d74569.gif)

**Comment by mwcz** [comment]
Huh... I have no idea why the gif recording looks like the dot is off-center.  I swear it is aligned perfectly! :)  Peek must be recording absolute mouse position or something.  It looks perfect in browser.

**Comment by Jared-Sprague** [comment]
http://www.teamxbow.org/downloads/mek04/data/crosshairs/triangle-05.png

**Comment by Jared-Sprague** [comment]
![triangle-05](https://cloud.githubusercontent.com/assets/3926730/26067430/3dd81eaa-3968-11e7-8a37-10f7df64187b.png)

**Comment by mwcz** [comment]
I think this is in good shape now.  what do you think @Jared-Sprague?

**Comment by Jared-Sprague** [comment]
I like the new cursor!
