### ISSUE TITLE
[bug] can get perfect if you destroy a wave of columns before next wave spawns

### ISSUE THREAD

**Issue by Jared-Sprague** [ScriptaGames/pityaboutearth#37]
if you destroy a column wave before the next wave spawns you can get perfect bonus.   This is because column barrage celestials aren't fully spawned when the barrage starts,but spawn every wave. 

To fix spawn all celestials when barrage fires

**Comment by mwcz** [comment]
I think this is cool :)

**Comment by Jared-Sprague** [comment]
call it a feature!
