### ISSUE TITLE
Loophole in the game

### ISSUE THREAD

**Issue by hybridx** [ScriptaGames/pityaboutearth#41]
### Unzip the screen recording

[Screen Recording 2020-10-30 at 12.23.27 PM.zip](https://github.com/ScriptaGames/pityaboutearth/files/5463432/Screen.Recording.2020-10-30.at.12.23.27.PM.zip)

### Contents in the screen recording (steps to reproduce)
- Open dev console and mark a breakpoint in config.js
- Remove the freeze on the Object and save the object so that it's mutable 
- Save the config file
- Go to dev console - console tab
- Change `config.BARRIER_WIDTH = 2`

**Comment by Jared-Sprague** [comment]
Nice dude! That's a clever hack! Thanks for the report, I think we'll just leave it for now since there is no global leaderboard or anything and it's just for fun.  If smart people want to hack it, I say go for it! :)
